@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

Class "<<interface>>\nAddressBookStorage" as AddressBookStorage


Class "<<interface>>\nLeavesBookStorage" as LeavesBookStorage

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -left-> "1" AddressBookStorage
StorageManager -right-> "1" LeavesBookStorage
StorageManager -down-> "1" UserPrefsStorage

Storage -down-|> AddressBookStorage
Storage -down-|> LeavesBookStorage
Storage -down-|> UserPrefsStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage

@enduml
